### ISSUE TITLE
Win10 最新版本無法直接使用 .exe 檔案轉換

### ISSUE THREAD

**Issue by mics8128** [Kutinging/EpubConv_Python#1]
Win10 1803
嘗試了兩台電腦
都會出現如下的錯誤
![default](https://user-images.githubusercontent.com/1339265/40765858-65ad0cd4-64e0-11e8-8d32-ee1af00d336a.png)

最後成功直接以 Python + opencc-python-reimplemented 相依套件 從原始碼成功執行

**Comment by Kutinging** [comment]
我目前還在找找這個錯誤的問題，因為我之前丟給同學測試
同樣是win10可以正常執行，我自己用虛擬機也會有同樣錯誤，現在推測試套件相依性的問題
我在嘗試看看

**Comment by Kutinging** [comment]
我找到問題點了，主要我在用pyinstaller包裝exe檔的時候我有使用到upx做加殼壓縮，後來我將加殼壓縮取消後在我的虛擬機是正常可以使用的，我等等重新包裝釋出再幫我嘗試看看~
